{% set name = "tslearn" %}
{% set version = "0.6.4" %}
{% set sha256 = "9efcd8afe3ef55186f57f4c3ccb45ae353d6f85f7aea2e420032c34a99345705" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: true  # [py2k]
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - python
    - pip
    - setuptools
    - cython
    - numpy
  run:
    - python
    - scipy
    - scikit-learn <1.7.0
    - numba
    - joblib

test:
  imports:
    - tslearn
    - tslearn.metrics

about:
  home: http://tslearn.readthedocs.io/
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  summary: A machine learning toolkit dedicated to time-series data
  description: |
    tslearn is a Python package that provides machine learning tools
    for the analysis of time series. This package builds on
    scikit-learn, numpy and scipy libraries.
  doc_url: http://tslearn.readthedocs.io/
  dev_url: https://github.com/rtavenar/tslearn

extra:
  recipe-maintainers:
    - rth
    - rtavenar
    - charavelg
