{% set name = "tslearn" %}
{% set version = "0.5.0.2" %}
{% set sha256 = "3bf859e3c8017513039e79fceebc4fe2f9e6acba49fbb15741de974474d92018" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: true  # [py2k]
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - cython
    - numpy
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - scipy
    - scikit-learn
    - numba
    - joblib

test:
  imports:
    - tslearn
    - tslearn.metrics

about:
  home: http://tslearn.readthedocs.io/
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  summary: A machine learning toolkit dedicated to time-series data
  description: |
    tslearn is a Python package that provides machine learning tools
    for the analysis of time series. This package builds on
    scikit-learn, numpy and scipy libraries.
  doc_url: http://tslearn.readthedocs.io/
  dev_url: https://github.com/rtavenar/tslearn

extra:
  recipe-maintainers:
    - rth
    - rtavenar
